#!/bin/bash
# Copyright (c) 2000-2021 Synology Inc. All rights reserved.

case ${MakeClean} in
    [Yy][Ee][Ss])
	# extract node
	tar xzf "node-linux-x64.tar.gz" -C app/ --strip-components=1 --no-same-owner
        ;;
esac

case ${CleanOnly} in
    [Yy][Ee][Ss])
        return
        ;;
esac

make ${MAKE_FLAGS}
