#!/bin/sh

GREEN='\033[1;32m'
CYAN='\033[0;36m'
NC='\033[0m'

PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w \$\[\033[00m\] "

printf "${GREEN}Homebridge Terminal for Synology DSM${NC}\n"
printf "${CYAN}Note: This is a restricted shell, sudo and npm cannot be used here.${NC}\n\n"

alias sudo='echo "ERROR: sudo / root access is not allowed by the homebridge service account. See https://kb.synology.com/en-id/DSM/tutorial/How_to_login_to_DSM_with_root_permission_via_SSH_Telnet \n" # '
alias npm='echo "ERROR: npm not available here. Use pnpm instead, eg: pnpm" '
