#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
  echo "This command must be executed as root or with sudo."
  exit 1
fi

printf "Entering Homebridge Shell. To exit type 'exit'.\n\n"

cd "$(readlink -f /var/packages/homebridge/shares/homebridge)"

exec sudo --user homebridge bash --rcfile /var/packages/homebridge/target/app/bashrc-hb-shell
