#!/bin/sh

### This script will be executed ONLY at package upgraded.
### Actions after package upgraded.
### ex. restore user settings.

cp $SYNOPKG_TEMP_UPGRADE_FOLDER/.env $SYNOPKG_PKGDEST/.env

# Enable safe mode if requested
if [ "$homebridge_pkgwizard_no_avahi_true" = "true" ]; then
	sed -i 's/homebridge:latest/homebridge:no-avahi/g' $SYNOPKG_PKGDEST/docker-compose.yml
else
	sed -i 's/homebridge:no-avahi/homebridge:latest/g' $SYNOPKG_PKGDEST/docker-compose.yml
fi

exit 0
