#!/bin/sh

### This script will be executed ONLY at package upgraded.
### Actions after package upgraded.
### ex. restore user settings.

cp $SYNOPKG_TEMP_UPGRADE_FOLDER/.env $SYNOPKG_PKGDEST/.env

exit 0
