#!/bin/sh

### This script will be executed when package installed and upgraded.

if [ "$SYNOPKG_PKG_STATUS" = "INSTALL" ]; then
	HOMEBRIDGE_TZ=$(synodate --getNameInTZDB)
	HOMEBRIDGE_PUID=$(id $SYNOPKG_USERNAME -u)
	HOMEBRIDGE_PGID=$(id $SYNOPKG_USERNAME -g)
	HOMEBRIDGE_VOL="$homebridge_pkgwizard_share_name"

	echo "HOMEBRIDGE_TZ=$HOMEBRIDGE_TZ
	HOMEBRIDGE_PUID=$HOMEBRIDGE_PUID
	HOMEBRIDGE_PGID=$HOMEBRIDGE_PGID
	HOMEBRIDGE_VOL=$HOMEBRIDGE_VOL" > $SYNOPKG_PKGDEST/.env

	chmod 755 $homebridge_pkgwizard_share_name
fi

cd $SYNOPKG_PKGDEST
docker-compose -f $SYNOPKG_PKGDEST/docker-compose.yml pull

exit 0
