#!/bin/sh

### This script will be execute when package installed and upgraded.
### Actions before package installed.
### ex. check environment.

# Remove any existing containers named 'homebridge'
docker rm -f homebridge

exit 0
