#!/bin/sh

### This script will be executed when package uninstalled and upgraded.
### Actions before package uninstalled
### ex. backup package data.

cd $SYNOPKG_PKGDEST
docker-compose -f $SYNOPKG_PKGDEST/docker-compose.yml down

exit 0
