#!/bin/sh

### This script will execute ONLY when package upgraded.
### Actions before package upgraded.
### ex. backup user settings for package upgrade.

cp $SYNOPKG_PKGDEST/.env $SYNOPKG_TEMP_UPGRADE_FOLDER/.env

exit 0
