#!/bin/bash
case "$1" in
    start)
        if [ "${EUID}" -eq 0 ]; then
            sudo -u homebridge synosystemctl start pkguser-homebridge
        else
            synosystemctl start pkguser-homebridge
        fi
        ;;
    stop)
        if [ "${EUID}" -eq 0 ]; then
            sudo -u homebridge synosystemctl stop pkguser-homebridge
        else
            synosystemctl stop pkguser-homebridge
        fi
        ;;
    status)
        if [ "${EUID}" -eq 0 ]; then
            sudo -u homebridge synosystemctl get-active-status pkguser-homebridge
        else
            synosystemctl get-active-status pkguser-homebridge
        fi
        ;;
    log)
        echo ""
        ;;
    *)
        echo "Usage: $0 {start|stop|status}" >&2
        exit 1
        ;;
esac
