#!/bin/bash
case "$1" in
    start)
	synosystemctl start pkguser-homebridge
        ;;
    stop)
	synosystemctl stop pkguser-homebridge
        ;;
    status)
        ;;
    log)
        echo ""
        ;;
    *)
        echo "Usage: $0 {start|stop|status}" >&2
        exit 1
        ;;
esac
exit 0
